#!/bin/bash

. /u/local/Modules/default/init/modules.sh
module load anaconda3/2023.03

# pgen prefix
pgen_prefix="/u/project/geschwind/shared/GenomicDatasets-processed/ACE-ANALYSIS/freeze0/SPARK/imputed/chr1"

# Specify the output CSV file
output_csv="individuals_list.csv"

# Run PLINK to generate the sample file
plink2 --pfile "${pgen_prefix}" --sample --out temp_individuals_list

# Extract FID and IID columns using awk, remove leading spaces with sed, and save to CSV
awk '{print $1, $2}' temp_individuals_list.sample | sed 's/^[[:space:]]*//' > "${output_csv}"

# Remove the temporary files generated by PLINK
rm temp_individuals_list.sample temp_individuals_list.log

echo "Individuals list saved to ${output_csv}"
